### 내 과목 조회하기 (전체 조회 포함)
//@no-log
GET {{host_url}}/v1/lectures/overviews?
    page={{roadmap.API_3_6.page}}&
    size={{roadmap.API_3_6.size}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 과목 이름 리스트 조회하기
//@no-log
GET {{host_url}}/v1/lectures/briefs
Authorization: Bearer {{access_token}}

### 로드맵 조회하기
//@no-log
GET {{host_url}}/v1/lectures/1/roadmaps
Authorization: Bearer {{access_token}}