### 내 과목 조회하기 (전체 조회 포함)
//@no-log
GET {{host_url}}/v1/lectures/overviews?
    page={{roadmap.API_3_6.page}}&
    size={{roadmap.API_3_6.size}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 과목 이름 리스트 조회하기
//@no-log
GET {{host_url}}/v1/lectures/briefs
Authorization: Bearer {{access_token}}

### 로드맵 조회하기
//@no-log
GET {{host_url}}/v1/lectures/1/roadmaps
Authorization: Bearer {{access_token}}

### 체크포인트 조회하기
//@no-log
GET {{host_url}}/v1/subtopics/1/check-points/summaries
Authorization: Bearer {{access_token}}

### 퀴즈 리스트 조회하기
//@no-log
GET {{host_url}}/v1/subtopics/1/check-points/quizzes/choices/summaries
Authorization: Bearer {{access_token}}


### 강의 생성하기
//@no-log
POST {{host_url}}/v1/lectures
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title" : "{{roadmap.API_3_7.title}}",
  "year": {{roadmap.API_3_7.year}},
  "semester": "{{roadmap.API_3_7.semester}}"
}


### pdf 등록하기
//@no-log
POST {{host_url}}/v1/roadmaps/lectures/{{roadmap.API_3_8.lectureId}}
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{access_token}}

--boundary
Content-Disposition: form-data; name="file"; filename="pdf1.pdf"
Content-Type: application/pdf

< /Users/jjuuuunnii/Desktop/Lecture4_AI.pdf

--boundary


### 퀴즈 정답 입력하기
//@no-log
POST {{host_url}}/v1/user-choices
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "user_quiz_list": [
    {
      "quiz_id": {{roadmap.API_3_5.user_quiz_list[0].quiz_id}},
      "choice_id": {{roadmap.API_3_5.user_quiz_list[0].choice_id}}
    },
    {
      "quiz_id": {{roadmap.API_3_5.user_quiz_list[1].quiz_id}},
      "choice_id": {{roadmap.API_3_5.user_quiz_list[1].choice_id}}
    },
    {
      "quiz_id": {{roadmap.API_3_5.user_quiz_list[2].quiz_id}},
      "choice_id": {{roadmap.API_3_5.user_quiz_list[2].choice_id}}
    }
  ]
}

### 최근 추가된 로드맵 조회하기
//@no-log
GET {{host_url}}/v1/roadmaps/created-at
Authorization: Bearer {{access_token}}
